version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "product-create:1:1,product-update:1:1,product-delete:1:1"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  invento-hub-product-service:
    image: codingwulf/invento-hub-product-service:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCT_CREATE_TOPIC=product-create
      - PRODUCT_UPDATE_TOPIC=product-update
      - PRODUCT_DELETE_TOPIC=product-delete
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_CONNECTION_STRING=jdbc:postgresql://product-db:5432/product
    depends_on:
      - kafka
      - product-db

  product-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product


  invento-hub-inventory-service:
    image: codingwulf/invento-hub-inventory-service:latest
    ports:
      - 8081:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCT_CREATE_TOPIC=product-create
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_CONNECTION_STRING=jdbc:postgresql://inventory-db:5432/inventory
    depends_on:
      - kafka
      - inventory-db

  inventory-db:
    image: postgres:latest
    ports:
      - 5666:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory






