version: '3'
services:
  invento-hub-product-service:
    image: codingwulf/invento-hub-product-service:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCT_CREATE_TOPIC=product-create
      - PRODUCT_UPDATE_TOPIC=product-update
      - PRODUCT_DELETE_TOPIC=product-delete
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_CONNECTION_STRING=jdbc:postgresql://product-db:5432/your_db
    depends_on:
      - kafka
      - product-db

  invento-hub-inventory-service:
    image: codingwulf/invento-hub-inventory-service:latest
    ports:
      - 8081:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCT_CREATE_TOPIC=product-create
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_CONNECTION_STRING=jdbc:postgresql://inventory-db:5432/your_db
    depends_on:
      - kafka
      - inventory-db

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  product-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db

  inventory-db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db
